package com.entity;
// Generated 31 déc. 2018 16:54:55 by Hibernate Tools 5.1.10.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact", catalog = "pfamini")
public class Contact implements java.io.Serializable {

	private ContactId id;

	public Contact() {
	}

	public Contact(ContactId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "nom", column = @Column(name = "nom", length = 254)),
			@AttributeOverride(name = "tel", column = @Column(name = "tel")) })
	public ContactId getId() {
		return this.id;
	}

	public void setId(ContactId id) {
		this.id = id;
	}

}
